// data/projects.ts
export const projects = [
  {
    slug: 'sabonnah-laundry-app',
    name: 'Sabonnah Laundry App',
    stars: 88,
    language: 'TypeScript',
    type: 'Mobile',
    languageColor: '#2b7489',
    forks: 45,
    imgHeight: 100,
    imgWidth: 200,
    description: 'A full-stack laundry service platform with dedicated apps for customers, vendors, and riders, plus an admin panel for real-time management and tracking',
    techStack: ['Next.js', 'NestJS', 'PostgreSQL', 'Twilio'],
    screenshots: [
      '/project-assets/sabonnah/screenshot-1.jpeg',
      '/project-assets/sabonnah/screenshot-2.jpeg',
      '/project-assets/sabonnah/screenshot-3.jpeg',
      '/project-assets/sabonnah/screenshot-4.jpeg',
      '/project-assets/sabonnah/screenshot-5.jpeg',
      '/project-assets/sabonnah/screenshot-6.jpeg',
      '/project-assets/sabonnah/screenshot-7.jpeg',
      '/project-assets/sabonnah/screenshot-8.jpeg',
      '/project-assets/sabonnah/screenshot-9.jpeg',
      '/project-assets/sabonnah/screenshot-10.jpeg',
      '/project-assets/sabonnah/screenshot-11.jpeg',
      '/project-assets/sabonnah/screenshot-12.jpeg',
      '/project-assets/sabonnah/screenshot-13.jpeg',
    ],
    points: [
      "Developed all app screens using React Native with Figma designs.",
      "Built backend with NestJS, Prisma, and PostgreSQL for handling vendors, riders, and customers.",
      "Implemented stack and tab navigation for a smooth UX.",
      "Integrated PayTabs payments using react-native-paytabs and managed transaction flows.",
      "Developed a voucher system with admin creation, customer redemption, and cron jobs for expiry & limits.",
      "Added tips feature allowing customers to send extra payments post-service.",
    ],
  },
  {
    slug: 'tutortrack',
    name: 'TutorTrack',
    stars: 120,
    language: 'TypeScript',
    type: 'Web',
    languageColor: '#2b7489',
    forks: 45,
    imgHeight: 400,
    imgWidth: 500,
    description: 'A global tutor scheduling and session management platform enabling tutors and students to seamlessly book and manage sessions with real-time timezone synchronization.',
    techStack: ['Next.js', 'Firebase', 'Tailwind CSS', 'Zustand'],
    screenshots: ['/project-assets/tutortrack/screenshot-1.png',
      '/project-assets/tutortrack/screenshot-2.png',
      '/project-assets/tutortrack/screenshot-3.png',
      '/project-assets/tutortrack/screenshot-4.png',
      '/project-assets/tutortrack/screenshot-5.png',
      '/project-assets/tutortrack/screenshot-6.png',
      '/project-assets/tutortrack/screenshot-7.png',
      '/project-assets/tutortrack/screenshot-8.png',
      '/project-assets/tutortrack/screenshot-9.png',
      '/project-assets/tutortrack/screenshot-10.png',
      '/project-assets/tutortrack/screenshot-11.png',
      '/project-assets/tutortrack/screenshot-12.png',
      '/project-assets/tutortrack/screenshot-13.png',
      '/project-assets/tutortrack/screenshot-14.png',
      '/project-assets/tutortrack/screenshot-15.png',
      '/project-assets/tutortrack/screenshot-16.png',
      '/project-assets/tutortrack/screenshot-17.png',
    ],
    points: [
      "Developed tutor and student management features with custom scheduling options (30 mins - 2.5 hours).",
      "Implemented booking conflict prevention, ensuring booked slots are instantly blocked for other students.",
      "Built global timezone support by storing and displaying schedules in UTC, ensuring cross-location consistency.",
      "Integrated Firebase Authentication with email verification for secure user onboarding.",
      "Utilized Firebase Realtime Database listeners for instant session and booking updates.",
      "Managed client-side state with Zustand for persistent and lightweight store management.",
      "Designed and developed responsive UI using Tailwind CSS and Next.js.",
    ]

  },
  {
    slug: 'acroworth',
    name: 'Acroworth',
    stars: 120,
    language: 'TypeScript',
    type: 'Web',
    languageColor: '#2b7489',
    forks: 45,
    imgHeight: 400,
    imgWidth: 500,
    description: 'A student support and scholarship platform connecting students and institutes, with real-time communication and advanced search features.',
    techStack: ['Next.js', 'Firebase', 'Tailwind CSS', 'Zustand'],
    screenshots:
      ['/project-assets/acroworth/screenshot-1.png',
        '/project-assets/acroworth/screenshot-2.png',
        '/project-assets/acroworth/screenshot-3.png',
      ],
    points: [
      "Developed real-time chat functionality enabling students and institutes to communicate seamlessly.",
      "Integrated Firebase Realtime Database for instant message delivery and updates.",
      "Implemented user-friendly chat UI using Next.js and Tailwind CSS.",
      "Currently building advanced search and filtering features for scholarships and institutes.",
      "Utilized Firebase Authentication for secure login and user management.",
      "Managed global state with Zustand for efficient and persistent data handling.",
      "Ensured responsive design across desktop and mobile devices."
    ]

  },
  {
    slug: 'mightyjoy',
    name: 'MightyJoy',
    stars: 120,
    language: 'TypeScript',
    type: 'Web',
    languageColor: '#2b7489',
    forks: 45,
    imgHeight: 400,
    imgWidth: 500,
    description: 'A dynamic influencer marketing agency dedicated to helping brands scale by building their own engaged communities.',
    techStack: ['Next.js', 'NestJS', 'PostgreSQL', 'Twilio', 'NextAuth'],
    screenshots: ['/project-assets/mightyjoy/screenshot-1.jpeg',
      '/project-assets/mightyjoy/screenshot-2.jpeg',
      '/project-assets/mightyjoy/screenshot-3.jpeg',
      '/project-assets/mightyjoy/screenshot-4.jpeg',
      '/project-assets/mightyjoy/screenshot-5.jpeg',
      '/project-assets/mightyjoy/screenshot-6.jpeg',
      '/project-assets/mightyjoy/screenshot-7.jpeg',
    ],
    points: [
      "Built and integrated REST APIs using React Query with NestJS backend.",
      "Managed Prisma models to handle evolving database schema requirements.",
      "Connected Instagram and TikTok via their basic OAuth APIs for influencer insights.",
      "Built UI components using Tailwind CSS and integrated dynamic state using Zustand.",
      "Enhanced chat system built with Twilio to improve real-time communication.",
    ],

  },
  {
    slug: 'david-hahklotubbe',
    name: 'David Hahklotubbe',
    link: 'https://david-website-kappa.vercel.app/',
    stars: 88,
    language: 'TypeScript',
    type: 'Web',
    languageColor: '#2b7489',
    forks: 45,
    description: 'A personal website for a Gerontologist and Public Speaker to showcase his mission, events, and publications using Next.js and Tailwind CSS',
    techStack: ['Next.js', 'Tailwind'],
    imgHeight: 400,
    imgWidth: 500,
    screenshots: [
      '/project-assets/david/screenshot-1.png',
      '/project-assets/david/screenshot-2.png',
      '/project-assets/david/screenshot-3.png',
      '/project-assets/david/screenshot-4.png',
      '/project-assets/david/screenshot-5.png',

    ],
    points: [
      "Developed a fully responsive personal website using Next.js and Tailwind CSS.",
      "Showcased David's work as a Gerontologist, Death Doula, and Public Speaker",
      "Collaborated closely with the client to align design and content with his personal mission of regret-free living",
    ],
  },
  {
    slug: 'makery',
    name: 'Makery',
    stars: 88,
    language: 'TypeScript',
    type: 'Web',
    languageColor: '#2b7489',
    forks: 45,
    description: '"Makery - AI Image Generator" is a dynamic web application that empowers users to create and purchase LoRA models',
    techStack: ['Next.js', 'NestJS', 'PostgreSQL', 'Twilio'],
    imgHeight: 400,
    imgWidth: 500,
    screenshots: ['/project-assets/makery/screenshot-1.png'],
    points: [
      "Integrated Stripe referral payment flows including coupons and checkout sessions.",
      "Created admin dashboards for managing creators and their linked Stripe accounts.",
      "Optimized checkout flows and UI/UX based on dynamic task requirements.",
      "Implemented secure and scalable PostgreSQL models to handle creator data.",
    ],
  },
  {
    slug: 'apptycoons',
    name: 'Apptycoons',
    stars: 88,
    language: 'TypeScript',
    type: 'Web',
    languageColor: '#2b7489',
    forks: 45,
    description: 'Official website of Apptycoons: NextJS web-app static ui pages.',
    techStack: ['Next.js'],
    screenshots: ['/project-assets/apptycoons/screenshot-1.jpeg'],
    imgHeight: 400,
    imgWidth: 500,
    points: [
      "Created responsive and dynamic UI pages from scratch using Next.js and Tailwind CSS.",
      "Improved CLS, TBT, and overall Lighthouse performance scores for SEO and UX.",
      "Implemented lazy loading, optimized assets, and responsive typography.",
    ],
  },
];

export const experiences = [
  {
    title: "Software Engineer I",
    company: "Sora Labs",
    period: "May 2024 - Present",
    current: true,
    skills: [
      "Next.js",
      "Firebase",
      "Zustand",
      "React Hook Form",
      "React Query",
      "ShadCN",
    ],
    points: [
      'Developed full-stack features for scheduling, booking, and real-time chat using <span class="text-[#58a6ff]">Next.js</span>, <span class="text-[#58a6ff]">Firebase</span>, and <span class="text-[#58a6ff]">Zustand</span>',
      'Implemented global timezone synchronization for booking systems using <span class="text-[#58a6ff]">UTC</span> handling logic',
      'Built conflict-free booking functionality with instant updates via <span class="text-[#58a6ff]">Firebase Realtime Database</span>',
      'Created responsive and user-friendly UIs with <span class="text-[#58a6ff]">Tailwind CSS</span>',
      'Integrated secure authentication flows with email verification using <span class="text-[#58a6ff]">Firebase Auth</span>',
      'Designed and optimized chat functionality for real-time student–institute communication',
      'Implemented advanced search and filtering features for scholarships and institute listings',
    ],
    projects: [
      {
        name: "TutorTrack",
        link: "/repos/tutortrack",
        description: "Next.js | Firebase | Zustand | Tailwind CSS",
        points: [
          'Developed tutor and student management features with custom scheduling options (30 mins – 2.5 hours) using <span class="text-[#58a6ff]">Next.js</span> and <span class="text-[#58a6ff]">Firebase</span>',
          'Implemented global timezone synchronization by storing and displaying schedules in <span class="text-[#58a6ff]">UTC</span>',
          'Built conflict-free booking functionality with instant updates via <span class="text-[#58a6ff]">Firebase Realtime Database</span>',
          'Integrated secure authentication and email verification with <span class="text-[#58a6ff]">Firebase Auth</span>',
          'Managed client-side state with <span class="text-[#58a6ff]">Zustand</span> and designed responsive UI using <span class="text-[#58a6ff]">Tailwind CSS</span>',
        ],
      },
      {
        name: "AcroWorth",
        link: "/repos/acroworth",
        description: "Next.js | Firebase | Zustand | Tailwind CSS",
        points: [
          'Developed real-time chat functionality enabling students and institutes to communicate instantly using <span class="text-[#58a6ff]">Firebase Realtime Database</span>',
          'Designed and implemented chat UI with <span class="text-[#58a6ff]">Next.js</span> and <span class="text-[#58a6ff]">Tailwind CSS</span>',
          'Integrated secure authentication with <span class="text-[#58a6ff]">Firebase Auth</span>',
          'Currently building advanced search and filtering features for scholarships and institute listings',
          'Managed application state with <span class="text-[#58a6ff]">Zustand</span> for efficient and persistent data handling',
        ],
      },
    ]
  },
  {
    title: "Associate Software Engineer",
    company: "Apptycoons",
    period: "Feb 2024 - April 2025",
    // current: true,
    skills: [
      "Next.js",
      "React Native",
      "NestJS",
      "PostgreSQL",
      "Prisma",
      "Stripe",
      "Paytab",
      "Zustand",
      "React Hook Form",
      "React Query",
      "MUI",
    ],
    points: [
      'Built and integrated full-stack features using <span class="text-[#58a6ff]">Next.js</span>, <span class="text-[#58a6ff]">NestJS</span>, and <span class="text-[#58a6ff]">React Query</span>',
      'Integrated <span class="text-[#58a6ff]">Stripe</span> for coupons, checkout sessions, webhooks, and referral payments',
      'Worked with <span class="text-[#58a6ff]">Prisma</span> to manage database schemas and PostgreSQL relationships',
      'Created responsive UIs and optimized performance (CLS, TBT) for web apps using <span class="text-[#58a6ff]">Tailwind CSS</span>',
      'Implemented subscriptions, webhooks, and coupon systems with <span class="text-[#58a6ff]">Stripe</span>',
    ],
    projects: [
      {
        name: "Sabonnah - Laundry App",
        link: "/repos/sabonnah-laundry-app",
        description: "React Native | NestJS | PostgreSQL | PayTabs",
        points: [
          'Developed customer, vendor, and rider apps using <span class="text-[#58a6ff]">React Native</span>',
          'Implemented backend with <span class="text-[#58a6ff]">NestJS</span> and <span class="text-[#58a6ff]">PostgreSQL</span>, including voucher and tips features',
          'Integrated <span class="text-[#58a6ff]">PayTabs</span> for payments and handled state with <span class="text-[#58a6ff]">React Query</span>',
        ],
      },
      {
        name: "MightyJoy",
        link: "/repos/mightyjoy",
        description: "Next.js | NestJS | Zustand",
        points: [
          'Built and integrated APIs using <span class="text-[#58a6ff]">React Query</span>',
          'Handled OAuth integration with <span class="text-[#58a6ff]">Instagram</span> and <span class="text-[#58a6ff]">TikTok</span>',
          'Implemented subscriptions, webhooks, and coupon systems with <span class="text-[#58a6ff]">Stripe</span>',
        ],
      },
      {
        name: "Makery",
        link: "/repos/makery",
        description: "Next.js | Stripe | PostgreSQL",
        points: [
          'Implemented referral payments and enhanced Stripe checkout session flow',
          'Improved UI and business logic based on task requirements',
        ],
      },
    ],
  },
  {
    title: "Software Engineering Intern",
    company: "Apptycoons",
    period: "Dec 2023 - Feb 2024",
    current: false,
    skills: [
      "Next.js",
      "Tailwind CSS",
      "Stripe",
      "Prisma",
      "NextAuth",
      "Zustand",
      "React Hook Form",
      "React Query",
      "MUI",
      "Twilio",
    ],
    points: [
      'Enhanced chat functionality using <span class="text-[#58a6ff]">Twilio</span>, improving performance and UX',
      'Contributed to production features across multiple apps built with <span class="text-[#58a6ff]">Next.js</span> and <span class="text-[#58a6ff]">Tailwind CSS</span>',
      'Created dynamic pricing tables and integrated <span class="text-[#58a6ff]">Stripe subscriptions</span> and coupons',
      'Worked on user onboarding and email flows using <span class="text-[#58a6ff]">NextAuth</span> and <span class="text-[#58a6ff]">Mailgun</span>',
      'Improved frontend performance through lazy loading, debouncing, and bundle optimization',
      'Collaborated with backend team on <span class="text-[#58a6ff]">Prisma schema design</span> and API integration',
    ],
    projects: [
      {
        name: "AppTycoons Website",
        link: "/repos/apptycoons",
        description: "Next.js | Tailwind CSS",
        points: [
          'Created dynamic UI pages and optimized performance metrics (CLS, TBT)',
        ],
      },
    ],
  },
  {
    title: "Data Journalist",
    company: "Raftar",
    period: "Dec 2022 - Dec 2023",
    current: false,
    skills: [
      "Data Storytelling",
      "Data Collection",
      "Web Scraping",
      "Twitter Open API",
      "Python",
      "Pandas",
      "Data Cleaning",
      "Power BI",
      "Data Visualization",
      "Concept Design",
      "Social Media Content",
      "Collaboration with Graphic Designers",
    ],
    points: [
      'Analyzing <span class="text-[#58a6ff]">data</span> and generating <span class="text-[#58a6ff]">insights</span>, furthermore creating creative storytelling visuals for their corporate clients.',
      'Analyzed <span class="text-[#58a6ff]">Twitter trends</span> and their impacts, generating insights and <span class="text-[#58a6ff]">data stories</span>.',
      'Used <span class="text-[#58a6ff]">AI tools</span> to generate <span class="text-[#58a6ff]">talk shows word frequency</span> related insights.',
      'Analyzed tweets from a year of 150 prominent <span class="text-[#58a6ff]">journalists</span> and generated insights out of it. Furthermore, transformed them into understandable and eye-pleasing <span class="text-[#58a6ff]">infographics</span> for <span class="text-[#58a6ff]">Raftar</span> to post.',
      'Confirming <span class="text-[#58a6ff]">trends</span> on Twitter, determining whether they are genuinely viral or just hyped up by <span class="text-[#58a6ff]">bots</span>.',
      'Working on <span class="text-[#58a6ff]">HEC</span>, <span class="text-[#58a6ff]">PBS</span>, and other official datasets, extracting insights and transforming them into creative and visually appealing <span class="text-[#58a6ff]">infographics</span> for Raftar\'s segment: <span class="text-[#58a6ff]">DataKahani</span>.',
    ],
    projects: [
      {
        name: "No Comments, Zero Reach",
        link: "https://www.linkedin.com/posts/omama-imran_dataanalysis-visualization-datavisualization-activity-7060974537563156480-UeUJ?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAC1P8U0Bq81JWg6T-vMOFXFc5oI8mYAVGL8",
        description: "Twitter API | Python | Power BI",
        points: [
          'Conducted a data analysis on the impact of the political campaign <span class="text-[#58a6ff]">\'NoCommentZeroReach\'</span> launched by PTI, focusing on engagement metrics of tweets by prominent PMLN members including Maryam Nawaz, Maryam Aurangzeb, Bilawal, and Shehbaz Sharif.',
          'Collected and analyzed data from 10 days before and after the campaign to measure its effect on the <span class="text-[#58a6ff]">reach and engagement</span> of political figures on Twitter.',
          'Visualized key findings using <span class="text-[#58a6ff]">Power BI</span> and collaborated with a <span class="text-[#58a6ff]">graphic designer</span> to create easy-to-understand infographics.',
        ],
      },
      {
        name: "Aaj Shahzaib 'KHANZIADA' ke saath",
        link: "https://www.linkedin.com/posts/omama-imran_content-media-ai-activity-7049734703024680962-RnP-?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAC1P8U0Bq81JWg6T-vMOFXFc5oI8mYAVGL8",
        description: "OPEN AI Whisper | Python | Data Analysis | Social Media Insights | MS Word",
        points: [
          'Transcribed 17 episodes of the talk show <span class="text-[#58a6ff]">\'Aaj Shahzeb Khanzada ke Saath\'</span> using <span class="text-[#58a6ff]">OpenAI Whisper</span>.',
          'Identified that <span class="text-[#58a6ff]">Imran Khan</span>\'s name was mentioned over 500 times in just 674 minutes of airtime — almost once per minute.',
          'Transformed this insight into a satirical narrative titled <span class="text-[#58a6ff]">\'Aaj Shahzaib Khanziada ke Saath\'</span> to highlight media focus bias.',
          'Designed and shared a visual summary of the findings with a graphic designer to emphasize political media trends.',
        ],
      },
      {
        name: "The Hidden Wealth of Toshakhana: Assessed vs. Paid",
        link: "https://www.linkedin.com/posts/omama-imran_visualization-storytelling-datastorytelling-activity-7045421576418115584-rL4v?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAC1P8U0Bq81JWg6T-vMOFXFc5oI8mYAVGL8",
        description: "Power BI | Data Cleaning | Kaggle Dataset | Political Insights",
        points: [
          'Pulled the Toshakhana dataset from <span class="text-[#58a6ff]">Kaggle</span> and conducted deep exploratory analysis.',
          'Used <span class="text-[#58a6ff]">Power BI</span> to clean, model, and visualize the assessed vs. retention cost data for political parties and institutions.',
          'Discovered how significantly the actual value of gifts remained <span class="text-[#58a6ff]">hidden beneath the surface</span>, visually represented through an iceberg metaphor.',
          'Designed the final infographic to communicate the disparity between reported and real value in an impactful, audience-friendly format.',
        ],
      },
      {
        name: "Political Insights from Journalists' Twitter Data",
        link: "https://www.linkedin.com/posts/omama-imran_dataanalysis-project-datavisualization-activity-7039279277422354432-fu7l?utm_source=social_share_send&utm_medium=member_desktop_web&rcm=ACoAAC1P8U0Bq81JWg6T-vMOFXFc5oI8mYAVGL8",
        description: "Python | Data Analysis | Power BI | Political Journalism",
        points: [
          'Scraped Twitter data from prominent 150 political journalists in Pakistan using <span class="text-[#58a6ff]">Python</span>.',
          'Conducted insightful analysis to uncover key political narratives and trends.',
          'Created interactive dashboards using <span class="text-[#58a6ff]">Power BI</span> to visualize the findings.',
          'Collaborated with graphic designers to turn the analysis into compelling visual stories, sharing ideas and reference pictures.',
          'Showcased the power of data visualization in transforming political data into impactful, accessible stories.',
        ],
      },
    ],
  },
];
